trigger:
  branches:
    include:
      - releases/*
      - refs/tags/v*

pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - aqt/*
    - ci/*
    - azure-pipelines.yml

jobs:
- job: MatricesGenerator
  displayName: Matrices Generator
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        addToPath: true
    - bash: python ci/generate_azure_pipelines_matrices.py
      name: mtrx
      displayName: Generate test matrices and set variables in Azure Pipelines

- job: Mac
  dependsOn: MatricesGenerator
  pool:
    vmImage: 'macOS-10.14'
  strategy:
    matrix: $[ dependencies.MatricesGenerator.outputs['mtrx.mac'] ]
  steps:
    - script: brew install p7zip
      displayName: Install 7zip
    - template: ci/steps.yml

- job: Windows
  dependsOn: MatricesGenerator
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix: $[ dependencies.MatricesGenerator.outputs['mtrx.windows'] ]
  steps:
    - template: ci/steps.yml

- job: Linux
  dependsOn: MatricesGenerator
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix: $[ dependencies.MatricesGenerator.outputs['mtrx.linux'] ]
  steps:
    - template: ci/steps.yml

- job: LinuxSpecificMirror
  displayName: Linux (Specific Mirror)
  variables:
    PYTHON_VERSION: '3.8'
    QT_VERSION: 5.13.1
    HOST: linux
    TARGET: android
    ARCH: android_armv7
    ARCHDIR: android_armv7
    QT_BASE_MIRROR: http://mirrors.ocf.berkeley.edu/qt/
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - template: ci/steps.yml

- job: LinuxSubArchives
  displayName: Linux (subarchive spcified)
  variables:
    PYTHON_VERSION: '3.8'
    QT_VERSION: 5.15.0
    HOST: linux
    TARGET: desktop
    ARCH: gcc_64
    ARCHDIR: gcc_64
    SUBARCHIVES: qtbase qttools qt icu
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - template: ci/steps.yml

- job: LinuxSrc
  displayName: Linux (source)
  variables:
    PYTHON_VERSION: '3.8'
    QT_VERSION: 6.0.0
    HOST: linux
    TARGET: desktop
    TOOL_NAME: src
    SUBARCHIVES: qt
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - template: ci/steps.yml

- job: LinuxExamples
  displayName: Linux (Examples)
  variables:
    PYTHON_VERSION: '3.8'
    QT_VERSION: 5.15.0
    HOST: linux
    TARGET: desktop
    TOOL_NAME: examples
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - template: ci/steps.yml

- job: LinuxDoc
  displayName: Linux (doc)
  variables:
    PYTHON_VERSION: '3.8'
    QT_VERSION: 5.15.0
    HOST: linux
    TARGET: desktop
    TOOL_NAME: doc
    SUBARCHIVES: qtdoc
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
    - template: ci/steps.yml
